apiVersion: keda.sh/v1alpha1
kind: ClusterTriggerAuthentication
metadata:
  name: dynatrace-keda-auth
  namespace: keda
spec:
  secretTargetRef:
  - parameter: apiKey
    name: dynatrace-keda-secret
    key: token