apiVersion: keda.sh/v1alpha1
kind: ClusterTriggerAuthentication
metadata:
  name: dynotrace-keda-token
spec:
  secretTargetRef:
    - parameter: apiKey
      name: dynotrace-low-token
      key: token