apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: testpod-kedascaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: testpod-deployment
  minReplicaCount:  0
  maxReplicaCount:  4
  triggers:
  - type: cron
    metadata:
      timezone: Europe/Sofia
      start: 00 00 * * 1-5
      end: 59 23 * * 1-5
      desiredReplicas: "2"
  - type: cpu
    metadata:
      type: Utilization
      value: "80"

  - type: metrics-api
    metadata:
      targetValue: '100'
      # TODO Replace <tenant-baseurl>
      url: 'https://dtz52610.live.dynatrace.com/api/v2/metrics/query?metricSelector=builtin:host.cpu.usage:splitBy("dt.entity.host"):avg:auto:sort(value(avg,descending)):limit(20)'
      valueLocation: 'result.0.data.0.values.0'
      authMode: apiKey
      keyParamName: Authorization
    authenticationRef:
      kind: ClusterTriggerAuthentication
      name: dynatrace-keda-auth