apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: testpod-kedascaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: testpod-deployment
  minReplicaCount:  0
  maxReplicaCount:  4
  triggers:
  - type: cron
    metadata:
      timezone: Europe/Sofia
      start: * * * * MON-FRI
      end: * * * * MON-FRI
      desiredReplicas: "1"
  - type: cpu
    metadata:
      type: Utilization
      value: "80"