apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: testpod-kedascaler
  namespace: testpod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: testpod-deployment
  minReplicaCount:  0
  maxReplicaCount:  4
  triggers:
    - type: metrics-api
      metadata:
        targetValue: "100"
        # TODO Replace <tenant-baseurl>
        url: 'https://dtz52610.live.dynatrace.com/api/v2/metrics/query?metricSelector=builtin:service.requestCount.total:filter(and(in("dt.entity.service",entitySelector("type(service),entityName(~"greeting-service~")")))):splitBy():sum:timeshift(-3m):rollup(avg,3m):last'
        valueLocation: 'result.0.data.0.values.0'
        authMode: apiKey
        keyParamName: Authorization
      authenticationRef:
        kind: ClusterTriggerAuthentication
        name: dynatrace-keda-auth